/*
全局变量
*/
let G = {};
/*API result*/
G.API_RESULT_SUCCESS = 0;
G.API_RESULT_FAIL = 1;

/*sim card State*/
G.SIM_STATE_NO_SIM = 0;
G.SIM_STATE_DETECTED = 1;
G.SIM_STATE_PIN = 2;
G.SIM_STATE_PUK = 3;
G.SIM_STATE_SIM_LOCK = 4;
G.SIM_STATE_PUK_TIMES_USED_OUT = 5;
G.SIM_STATE_INVALID = 6;
G.SIM_STATE_READY = 7;
G.SIM_STATE_INITING = 11;

/*wan status*/
G.WAN_STATE_DISCONNECTED = 0;
G.WAN_STATE_CONNECTING = 1;
G.WAN_STATE_CONNECTED = 2;
G.WAN_STATE_DISCONNECTING = 3;

/***************SIM Lock Status**********************/
G.SIMLOCK_PERSO_NONE_REQUIRED = -1; /*no sim lock/sim lock unlock*/
G.SIMLOCK_PERSO_NET_PIN_REQUIRED = 0; /*nck*/
G.SIMLOCK_PERSO_NETSUB_PIN_REQUIRED = 1; /*nsck*/
G.SIMLOCK_PERSO_SP_PIN_REQUIRED = 2; /*spck*/
G.SIMLOCK_PERSO_CORP_PIN_REQUIRED = 3; /*cck*/
G.SIMLOCK_PERSO_PH_FSIM_PIN_REQUIRED = 4; /*pck*/

G.SIMLOCK_PERSO_NET_PUK_REQUIRED = 15; /*rck*/
G.SIMLOCK_PERSO_NETSUB_PUK_REQUIRED = 16;
G.SIMLOCK_PERSO_SP_PUK_REQUIRED = 17;
G.SIMLOCK_PERSO_CORP_PUK_REQUIRED = 18;
G.SIMLOCK_PERSO_PH_FSIM_PUK_REQUIRED = 19;
G.SIMLOCK_PERSO_RCK_FORBID = 30; /*rck forbid*/

/****auto pin state *****/
G.SIM_AUTO_PIN_DISABLE = 0;
G.SIM_AUTO_PIN_ENABLE = 1;

/*roam State*/
G.ROAM_STATE_YES = 0;
G.ROAM_STATE_NO = 1;

/*network type*/

G.NETWORK_TYPE_NO_SERVICE = 0;
G.NETWORK_TYPE_GPRS = 1;
G.NETWORK_TYPE_EDGE = 2;
G.NETWORK_TYPE_HSPA = 3;
G.NETWORK_TYPE_HSUPA = 4;
G.NETWORK_TYPE_UMTS = 5; /*UMTS means WCDMA*/
G.NETWORK_TYPE_HSPA_PLUS = 6;
G.NETWORK_TYPE_DC_HSPA_PLUS = 7;
G.NETWORK_TYPE_LTE = 8;
G.NETWORK_TYPE_LTE_PLUS = 9;
G.NETWORK_TYPE_CDMA = 10; //CDMA means CDMA-EX
G.NETWORK_TYPE_GSM = 11;
G.NETWORK_TYPE_EVDO = 12; //EVDO means CDMA-EVDO
G.NETWORK_TYPE_LTE_FDD = 13;
G.NETWORK_TYPE_LTE_TDD = 14;

/*network search state*/
G.NETWORK_SEARCH_STATE_NONE = 0;
G.NETWORK_SEARCH_STATE_SEARCHING = 1;
G.NETWORK_SEARCH_STATE_SUCCESSFUL = 2;
G.NETWORK_SEARCH_STATE_FAILED = 3;

/*network register state*/
G.NETWORK_REGISTER_STATE_NONE = 0;
G.NETWORK_REGISTER_STATE_REGISTERING = 1;
G.NETWORK_REGISTER_STATE_SUCCESSFUL = 2;
G.NETWORK_REGISTER_STATE_FAILED = 3;

//wlan Mode Ghz
G.WLAN_MODE_2GHZ = 0;
G.WLAN_MODE_5GHZ = 1;
G.WLAN_MODE_2GHZ_5GHZ = 2;
/*wlan status*/
G.WLAN_STATE_DISABLED = 0;
G.WLAN_STATE_ENABLED = 1;
G.WLAN_STATE_WPS = 2;
/*ssid hidden State*/
G.WLAN_SSID_HIDDEN_DISABLE = 0;
G.WLAN_SSID_HIDDEN_ENABLE = 1;

/*security*/
G.SECRUTIY_TYPE_DISABLE = 0;
G.SECRUTIY_TYPE_WEP = 1;
G.SECRUTIY_TYPE_WPA_PSK = 2;
G.SECRUTIY_TYPE_WPS2_PSK = 3;
G.SECRUTIY_TYPE_WPA_MIXED = 4;

/*wpa type*/
G.WPA_TYPE_AES = 1;
G.WPA_TYPE_TKIP = 0;
G.WPA_TYPE_AUTO = 2;

/* network mode*/
G.NETWORK_MODE_AUTO = 4;
G.NETWORK_MODE_2G_ONLY = 13;
G.NETWORK_MODE_3G_ONLY = 14;

/* network state*/
G.NETWORK_STATE_AVAILABLE = 1; //可用
G.NETWORK_STATE_CURRENT = 2; //当前注册
G.NETWORK_STATE_FORBIDDEN = 3; //不可用

/* network rat*/
G.NETWORK_RAT_TYPE_GSM = 1;
G.NETWORK_RAT_TYPE_UMTS = 2;
G.NETWORK_RAT_TYPE_LTE = 3;
G.NETWORK_RAT_TYPE_UNKNOWN = 4;

/* update check status*/
G.VERSION_CHECKING = 0;
G.VERSION_NEW_YES = 1;
G.VERSION_NEW_NO = 2;
G.VERSION_NO_CONNECT = 3;
G.VERSION_NO_SERVICE = 4;
G.VERSION_CHECK_ERROR = 5;

/* update download status*/
G.FOTA_DOWNLOAD_STATE_FREE = 0;
G.FOTA_DOWNLOAD_STATE_DOWNLOADING = 1;
G.FOTA_DOWNLOAD_STATE_COMPLETED = 2;

G.FOTA_BATTERY_STATE_ON_ENOUGH = 0;
G.FOTA_BATTERY_STATE_ENOUGH = 1;

/* mac filter state*/
G.MAC_FILTER_POLICY_DISABLE = 0;
G.MAC_FILTER_POLICY_ALLOW = 1;
G.MAC_FILTER_POLICY_DENY = 2;
G.MAC_FILTER_STATE_DENYMAX = 10;

/****get sms init status****/
G.SMS_INIT_STATUS_COMPLETE = 0; //sms init complete
G.SMS_INIT_STATUS_INITING = 1; //sms is initing

/****get sms type****/
G.SMS_LIST_SMS_TYPE_READ = 0; // read
G.SMS_LIST_SMS_TYPE_UNREAD = 1; // unread
G.SMS_LIST_SMS_TYPE_SENT = 2; // sent
G.SMS_LIST_SMS_TYPE_SENT_FAILED = 3; // sent failed
G.SMS_LIST_SMS_TYPE_REPORT = 4; // report
G.SMS_LIST_SMS_TYPE_FLASH = 5; // flash
G.SMS_LIST_SMS_TYPE_DRAFT = 6; // draft

/****delete sms type****/
G.SMS_DELETE_FLAG_ALL = 0; //delete all SMS
G.SMS_DELETE_FLAG_Contact = 1; // delete one record in Contact SMS list
G.SMS_DELETE_FLAG_Content = 2; //delete one record in Content  SMS list

/****send & save sms id****/
G.SMS_SEND_SAVE_NEW = -1; //-1 means send or save a new sms.

/****get sms send status***/
G.SMS_SEND_STATUS_NONE = 0; // none
G.SMS_SEND_STATUS_SENDING = 1; // sending
G.SMS_SEND_STATUS_SUCCESS = 2; // success
G.SMS_SEND_STATUS_FAIL_SENDING = 3; // failstill sending last message
G.SMS_SEND_STATUS_FULL = 4; // fail with Memory full
G.SMS_SEND_STATUS_FAILED = 5; // fail

/****sms setting************/
G.SMS_SETTING_REPORT_DISABLE = 0; //report disable
G.SMS_SETTING_REPORT_ENABLE = 1; //report enable
G.SMS_SETTING_STORE_SIM = 0; //sms store in sim card
G.SMS_SETTING_STORE_DEVICE = 1; //sms store in device

/*****battery charging******/
G.BATTERY_CHARGING = 0;
G.BATTERY_CHARGING_FULL = 1;
G.BATTERY_CHARGING_OTHING = 2;

/***********Connected Devices Type**************/
G.CONNDEVICE_LOGINED_DEVICE = 0;
G.CONNDEVICE_CONNECTEDONLY_DEVICE = 1;

/***********Connected Devices ConnectMode**************/
G.CONNDEVICE_USB_DEVICE = 0;
G.CONNDEVICE_WIFI_DEVICE = 1;

/*usage setting*/
G.USAGE_TIME_LIMIT_ENABLE = 1;
G.USAGE_TIME_LIMIT_DISABLE = 0;

G.USAGE_AUTO_DISCONN_ENABLE = 1;
G.USAGE_AUTO_DISCONN_DISABLE = 0;

/*sms status*/
G.MACRO_SMS_DISENABLE = 0;
G.MACRO_SMS_FULL = 1;
G.MACRO_SMS_NORMAL = 2;
G.MACRO_SMS_NEW = 3;

/*statistics unit status*/
G.statistics_MB = 0;
G.statistics_GB = 1;
G.statistics_TB = 2;

/*WAN connect type*/
G.WAN_CONNECT_TYPE_PPPoE = 0;
G.WAN_CONNECT_TYPE_STATIC_IP = 2;
G.WAN_CONNECT_TYPE_DHCP = 1;

/*WAN port connect status*/
G.WAN_PORT_STATUS_DISCONNECTED = 0;
G.WAN_PORT_STATUS_CONNECTING = 1;
G.WAN_PORT_STATUS_CONNECTED = 2;
G.WAN_PORT_STATUS_DISCONNECTING = 3;

/*WAN port Internet connect status*/
G.WAN_PORT_INTERNET_DISCONNECTED = 0;
G.WAN_PORT_INTERNET_CONNECTED = 2;

/*WAN MAC Address change type*/
G.WAN_MAC_ADDRESS_CLONE = 0;
G.WAN_MAC_ADDRESS_RESTORE = 1;

/*wlan 2.4ghz and 5ghz*/
G.WLAN_MODEL_ApStatus_DISABLE = 0;
G.WLAN_MODEL_ApStatus_ENABLE = 1;

G.WLAN_MODEL_SecurityMode_DISABLE = 0;
G.WLAN_MODEL_SecurityMode_WEP = 1;
G.WLAN_MODEL_SecurityMode_WPA = 2;
G.WLAN_MODEL_SecurityMode_WPA2 = 3;
G.WLAN_MODEL_SecurityMode_WPAWPA2 = 4;


export default G;
