/*
全局变量
*/
let sys = {};

/*TimeZone*/
sys.ZoneName = [
  ["UTC","UTC"],
  ["WET0WEST,M3.5.0/1,M10.5.0","Atlantic/Faroe"],
  ["NFT-11:30","Pacific/Norfolk"],
  ["ART3","America/Argentina/Cordoba"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Simferopol"],
  ["WST-8","Antarctica/Casey"],
  ["ART3","America/Argentina/La Rioja"],
  ["BTT-6","Asia/Thimphu"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Budapest"],
  ["SYOT-3","Antarctica/Syowa"],
  ["CST6","America/El Salvador"],
  ["SCT-4","Indian/Mahe"],
  ["MST7MDT,M3.2.0,M11.1.0","America/Boise"],
  ["AST4","America/St Thomas"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Gibraltar"],
  ["WST-13","Pacific/Apia"],
  ["FET-3","Europe/Minsk"],
  ["CKT10","Pacific/Rarotonga"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Arctic/Longyearbyen"],
  ["CST-8","Asia/Shanghai"],
  ["CST6CDT,M3.2.0,M11.1.0","America/North Dakota/New Salem"],
  ["EET-2","Africa/Tripoli"],
  ["PET5","America/Lima"],
  ["AMT4","America/Rio Branco"],
  ["WAT-1","Africa/Libreville"],
  ["PONT-11","Pacific/Pohnpei"],
  ["GMT0IST,M3.5.0/1,M10.5.0","Europe/Dublin"],
  ["HAST10HADT,M3.2.0,M11.1.0","America/Adak"],
  ["QYZT-6","Asia/Qyzylorda"],
  ["IOT-6","Indian/Chagos"],
  ["MYT-8","Asia/Kuching"],
  ["FET-3","Europe/Kaliningrad"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Sofia"],
  ["CST-8","Asia/Taipei"],
  ["PST8PDT,M3.2.0,M11.1.0","America/Dawson"],
  ["GMT0","Africa/Banjul"],
  ["AMT4AMST,M10.3.0/0,M2.3.0/0","America/Campo Grande"],
  ["CAT-2","Africa/Blantyre"],
  ["CST6CDT,M3.2.0,M11.1.0","America/Rankin Inlet"],
  ["CAT-2","Africa/Bujumbura"],
  ["WAT-1","Africa/Luanda"],
  ["AST4","America/Marigot"],
  ["GMT0","Atlantic/St Helena"],
  ["ALMT-6","Asia/Almaty"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Vaduz"],
  ["MST7MDT,M3.2.0,M11.1.0","America/Inuvik"],
  ["EET-2","Asia/Hebron"],
  ["MST7MDT,M4.1.0,M10.5.0","America/Mazatlan"],
  ["AST4","America/Curacao"],
  ["WAT-1","Africa/Ndjamena"],
  ["AST-3","Asia/Kuwait"],
  ["GMT0","Africa/Nouakchott"],
  ["ROTT3","Antarctica/Rothera"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Uzhgorod"],
  ["GMT0","Africa/Bamako"],
  ["MST7","America/Phoenix"],
  ["CST6","America/Costa Rica"],
  ["GST2","Atlantic/South Georgia"],
  ["MHT-12","Pacific/Majuro"],
  ["EST5","America/Port-au-Prince"],
  ["YEKT-6","Asia/Yekaterinburg"],
  ["CST-8","Asia/Kashgar"],
  ["CET-1","Africa/Algiers"],
  ["AMT4","America/Eirunepe"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Vilnius"],
  ["WET0","Africa/Casablanca"],
  ["ANAT-12","Asia/Anadyr"],
  ["MST7MDT,M3.2.0,M11.1.0","America/Edmonton"],
  ["WET0","Africa/El Aaiun"],
  ["WET0WEST,M3.5.0/1,M10.5.0","Atlantic/Canary"],
  ["ART3","America/Argentina/Rio Gallegos"],
  ["ART3","America/Argentina/Ushuaia"],
  ["MST7MDT,M3.2.0,M11.1.0","America/Denver"],
  ["PHOT-13","Pacific/Enderbury"],
  ["CST6CDT,M3.2.0,M11.1.0","America/Resolute"],
  ["AST4ADT,M3.2.0,M11.1.0","America/Goose Bay"],
  ["CST6","America/Regina"],
  ["CST-8","Asia/Macau"],
  ["EAT-3","Africa/Dar es Salaam"],
  ["WAT-1","Africa/Kinshasa"],
  ["CST6CDT,M4.1.0,M10.5.0","America/Bahia Banderas"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Madrid"],
  ["TLT-9","Asia/Dili"],
  ["MAWT-5","Antarctica/Mawson"],
  ["MST7MDT,M3.2.0,M11.1.0","America/Ojinaga"],
  ["NUT11","Pacific/Niue"],
  ["AST4","America/Anguilla"],
  ["WAT-1","Africa/Bangui"],
  ["CXT-7","Indian/Christmas"],
  ["MVT-5","Indian/Maldives"],
  ["AST4","America/Barbados"],
  ["PETT-12","Asia/Kamchatka"],
  ["GFT3","America/Cayenne"],
  ["VOLT-4","Europe/Volgograd"],
  ["AST4","America/St Lucia"],
  ["CWST-8:45","Australia/Eucla"],
  ["LINT-14","Pacific/Kiritimati"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Sarajevo"],
  ["MST7","America/Dawson Creek"],
  ["AST4","America/Antigua"],
  ["CET-1","Africa/Tunis"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Indiana/Vevay"],
  ["EAT-3","Africa/Asmara"],
  ["AQTT-5","Asia/Aqtobe"],
  ["KOST-11","Pacific/Kosrae"],
  ["CVT1","Atlantic/Cape Verde"],
  ["GMT0","Africa/Lome"],
  ["CHOT-8","Asia/Choibalsan"],
  ["WIT-7","Asia/Jakarta"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Indiana/Winamac"],
  ["AKST9AKDT,M3.2.0,M11.1.0","America/Yakutat"],
  ["AST4","America/Dominica"],
  ["CST6CDT,M3.2.0,M11.1.0","America/Rainy River"],
  ["CST6","America/Belize"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Indiana/Vincennes"],
  ["ORAT-5","Asia/Oral"],
  ["TOT-13","Pacific/Tongatapu"],
  ["BRT3","America/Recife"],
  ["ChST-10","Pacific/Guam"],
  ["CST-8","Asia/Chongqing"],
  ["TMT-5","Asia/Ashgabat"],
  ["BRT3","America/Fortaleza"],
  ["CST6CDT,M3.2.0,M11.1.0","America/Indiana/Tell City"],
  ["AST4","America/St Barthelemy"],
  ["ICT-7","Asia/Bangkok"],
  ["WAT-1WAST,M9.1.0,M4.1.0","Africa/Windhoek"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Podgorica"],
  ["EGT1EGST,M3.5.0/0,M10.5.0/1","America/Scoresbysund"],
  ["WAT-1","Africa/Lagos"],
  ["MST7MDT,M3.2.0,M11.1.0","America/Cambridge Bay"],
  ["CAT-2","Africa/Gaborone"],
  ["AST4","America/Port of Spain"],
  ["WAT-1","Africa/Malabo"],
  ["CST6CDT,M3.2.0,M11.1.0","America/Menominee"],
  ["EAT-3","Africa/Djibouti"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Mariehamn"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Riga"],
  ["ART3","America/Argentina/Salta"],
  ["MST7MDT,M3.2.0,M11.1.0","America/Shiprock"],
  ["AST-3","Asia/Qatar"],
  ["AST4","America/Guadeloupe"],
  ["WFT-12","Pacific/Wallis"],
  ["CST6","America/Guatemala"],
  ["WAKT-12","Pacific/Wake"],
  ["AST4ADT,M3.2.0,M11.1.0","America/Moncton"],
  ["PMST3PMDT,M3.2.0,M11.1.0","America/Miquelon"],
  ["TAHT10","Pacific/Tahiti"],
  ["CST6CDT,M4.1.0,M10.5.0","America/Monterrey"],
  ["AST4","America/Tortola"],
  ["ChST-10","Pacific/Saipan"],
  ["AST4ADT,M3.2.0,M11.1.0","America/Thule"],
  ["EET-2EEST,M3.5.0/0,M10.5.0/0","Asia/Beirut"],
  ["AST4","America/Aruba"],
  ["MUT-4","Indian/Mauritius"],
  ["PGT-10","Pacific/Port Moresby"],
  ["MST7MDT,M3.2.0,M11.1.0","America/Yellowknife"],
  ["OMST-7","Asia/Omsk"],
  ["CST-9:30","Australia/Darwin"],
  ["PWT-9","Pacific/Palau"],
  ["GMT0","Africa/Sao Tome"],
  ["NCT-11","Pacific/Noumea"],
  ["AZOT1AZOST,M3.5.0/0,M10.5.0/1","Atlantic/Azores"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Paris"],
  ["NRT-12","Pacific/Nauru"],
  ["SST11","Pacific/Midway"],
  ["KST-9","Asia/Seoul"],
  ["WST-8","Australia/Perth"],
  ["PYT4PYST,M10.1.0/0,M4.2.0/0","America/Asuncion"],
  ["MHT-12","Pacific/Kwajalein"],
  ["AST-3","Asia/Bahrain"],
  ["AST-3","Asia/Baghdad"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Malta"],
  ["BRT3BRST,M10.3.0/0,M2.3.0/0","America/Sao Paulo"],
  ["EAT-3","Africa/Khartoum"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Tirane"],
  ["KGT-6","Asia/Bishkek"],
  ["HST10","Pacific/Johnston"],
  ["GAMT9","Pacific/Gambier"],
  ["EST5EDT,M3.2.0,M11.1.0","America/New York"],
  ["EET-2EEST,M4.1.5/0,M10.5.5/0","Asia/Damascus"],
  ["IST-5:30","Asia/Colombo"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Brussels"],
  ["TVT-12","Pacific/Funafuti"],
  ["GMT0","America/Danmarkshavn"],
  ["FJT-12","Pacific/Fiji"],
  ["BRT3","America/Santarem"],
  ["VET4:30","America/Caracas"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Nassau"],
  ["TKT10","Pacific/Fakaofo"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Detroit"],
  ["VUT-11","Pacific/Efate"],
  ["CHUT-10","Pacific/Chuuk"],
  ["CST6CDT,M3.2.0,M11.1.0","America/North Dakota/Center"],
  ["CHAST-12:45CHADT,M9.5.0/2:45,M4.1.0/3:45","Pacific/Chatham"],
  ["EST5","America/Panama"],
  ["MYT-8","Asia/Kuala Lumpur"],
  ["MeST8","America/Metlakatla"],
  ["PST8PDT,M3.2.0,M11.1.0","America/Vancouver"],
  ["CST6CDT,M3.2.0,M11.1.0","America/Winnipeg"],
  ["RET-4","Indian/Reunion"],
  ["EAT-3","Indian/Mayotte"],
  ["SAKT-11","Asia/Sakhalin"],
  ["AMT4","America/Manaus"],
  ["UZT-5","Asia/Tashkent"],
  ["TFT-5","Indian/Kerguelen"],
  ["MST7","America/Hermosillo"],
  ["GST-4","Asia/Dubai"],
  ["EST-10EST,M10.1.0,M4.1.0/3","Australia/Hobart"],
  ["BRT3BRST,M10.3.0/0,M2.3.0/0","America/Bahia"],
  ["CCT-6:30","Indian/Cocos"],
  ["LHST-10:30LHST-11,M10.1.0,M4.1.0","Australia/Lord Howe"],
  ["EAT-3","Indian/Antananarivo"],
  ["ART3","America/Argentina/Jujuy"],
  ["EAT-3","Africa/Mogadishu"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Zurich"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Zaporozhye"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Zagreb"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Warsaw"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Vienna"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Vatican"],
  ["SBT-11","Pacific/Guadalcanal"],
  ["AKST9AKDT,M3.2.0,M11.1.0","America/Nome"],
  ["PST8","Pacific/Pitcairn"],
  ["ART3","America/Argentina/San Juan"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Kiev"],
  ["CST6CDT,M4.1.0,M10.5.0","America/Mexico City"],
  ["AST-3","Asia/Aden"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Skopje"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/San Marino"],
  ["AST4","America/Kralendijk"],
  ["CST6","America/Swift Current"],
  ["CAT-2","Africa/Maputo"],
  ["AST4ADT,M3.2.0,M11.1.0","Atlantic/Bermuda"],
  ["DDUT-10","Antarctica/DumontDUrville"],
  ["SAMT-4","Europe/Samara"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Rome"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Prague"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Oslo"],
  ["MSK-4","Europe/Moscow"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Monaco"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Luxembourg"],
  ["PST8PDT,M4.1.0,M10.5.0","America/Santa Isabel"],
  ["GMT0BST,M3.5.0/1,M10.5.0","Europe/London"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Ljubljana"],
  ["WET0WEST,M3.5.0/1,M10.5.0","Europe/Lisbon"],
  ["VLAT-11","Asia/Vladivostok"],
  ["GMT0BST,M3.5.0/1,M10.5.0","Europe/Jersey"],
  ["NZST-12NZDT,M9.5.0,M4.1.0/3","Antarctica/South Pole"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Grand Turk"],
  ["AKST9AKDT,M3.2.0,M11.1.0","America/Anchorage"],
  ["CST6","America/Managua"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Belgrade"],
  ["AST4","America/Montserrat"],
  ["EAT-3","Indian/Comoro"],
  ["GMT0","Africa/Bissau"],
  ["AQTT-5","Asia/Aqtau"],
  ["CST6","America/Tegucigalpa"],
  ["CIT-8","Asia/Makassar"],
  ["ECT5","America/Guayaquil"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Indiana/Marengo"],
  ["ULAT-8","Asia/Ulaanbaatar"],
  ["CST6CDT,M3.2.0,M11.1.0","America/North Dakota/Beulah"],
  ["MAGT-12","Asia/Magadan"],
  ["GMT0","Africa/Abidjan"],
  ["AMT4","America/Porto Velho"],
  ["CAT-2","Africa/Lubumbashi"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Chisinau"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Bucharest"],
  ["GALT6","Pacific/Galapagos"],
  ["CST6CDT,M4.1.0,M10.5.0","America/Cancun"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Indiana/Petersburg"],
  ["UZT-5","Asia/Samarkand"],
  ["IRKT-9","Asia/Irkutsk"],
  ["CST-8","Asia/Harbin"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Thunder Bay"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Pangnirtung"],
  ["AST4","America/Santo Domingo"],
  ["AST4","America/Puerto Rico"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Istanbul"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Athens"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Andorra"],
  ["NOVT-7","Asia/Novokuznetsk"],
  ["EST-10EST,M10.1.0,M4.1.0/3","Australia/Sydney"],
  ["VOST-6","Antarctica/Vostok"],
  ["AFT-4:30","Asia/Kabul"],
  ["EST-10","Australia/Lindeman"],
  ["PST8PDT,M3.2.0,M11.1.0","America/Whitehorse"],
  ["EST-10EST,M10.1.0,M4.1.0/3","Australia/Melbourne"],
  ["EAT-3","Africa/Juba"],
  ["CAT-2","Africa/Kigali"],
  ["GMT0BST,M3.5.0/1,M10.5.0","Europe/Isle of Man"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Tallinn"],
  ["PKT-5","Asia/Karachi"],
  ["EAT-3","Africa/Addis Ababa"],
  ["EST-10EST,M10.1.0,M4.1.0/3","Australia/Currie"],
  ["CST-9:30CST,M10.1.0,M4.1.0/3","Australia/Broken Hill"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Kentucky/Monticello"],
  ["BNT-8","Asia/Brunei"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Montreal"],
  ["WAT-1","Africa/Porto-Novo"],
  ["CST-9:30CST,M10.1.0,M4.1.0/3","Australia/Adelaide"],
  ["FKT4FKST,M9.1.0,M4.3.0","Atlantic/Stanley"],
  ["GMT0","Africa/Accra"],
  ["WET0WEST,M3.5.0/1,M10.5.0","Atlantic/Madeira"],
  ["DAVT-7","Antarctica/Davis"],
  ["AMT-4AMST,M3.5.0,M10.5.0/3","Asia/Yerevan"],
  ["SAST-2","Africa/Maseru"],
  ["CAT-2","Africa/Harare"],
  ["YAKT-10","Asia/Yakutsk"],
  ["SST11","Pacific/Pago Pago"],
  ["WIT-7","Asia/Pontianak"],
  ["NZST-12NZDT,M9.5.0,M4.1.0/3","Antarctica/McMurdo"],
  ["KST-9","Asia/Pyongyang"],
  ["AST-3","Asia/Riyadh"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Kentucky/Louisville"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Europe/Helsinki"],
  ["WAT-1","Africa/Brazzaville"],
  ["EAT-3","Africa/Nairobi"],
  ["AKST9AKDT,M3.2.0,M11.1.0","America/Sitka"],
  ["JST-9","Asia/Tokyo"],
  ["AZT-4AZST,M3.5.0/4,M10.5.0/5","Asia/Baku"],
  ["AST4ADT,M3.2.0,M11.1.0","America/Glace Bay"],
  ["EST5","America/Jamaica"],
  ["CST5CDT,M3.2.0/0,M10.5.0/1","America/Havana"],
  ["AKST9AKDT,M3.2.0,M11.1.0","America/Juneau"],
  ["SGT-8","Asia/Singapore"],
  ["BRT3","America/Araguaina"],
  ["MART9:30","Pacific/Marquesas"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Bratislava"],
  ["CST-8","Asia/Urumqi"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Nipigon"],
  ["MMT-6:30","Asia/Rangoon"],
  ["UYT3UYST,M10.1.0,M3.2.0","America/Montevideo"],
  ["SAST-2","Africa/Mbabane"],
  ["ICT-7","Asia/Ho Chi Minh"],
  ["ICT-7","Asia/Phnom Penh"],
  ["AST4","America/Lower Princes"],
  ["MST7MDT,M4.1.0,M10.5.0","America/Chihuahua"],
  ["NOVT-7","Asia/Novosibirsk"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Amsterdam"],
  ["CST6CDT,M3.2.0,M11.1.0","America/Indiana/Knox"],
  ["GST-4","Asia/Muscat"],
  ["PHT-8","Asia/Manila"],
  ["AST4","America/Blanc-Sablon"],
  ["GMT0BST,M3.5.0/1,M10.5.0","Europe/Guernsey"],
  ["AST4","America/St Kitts"],
  ["AST4","America/Martinique"],
  ["EIT-9","Asia/Jayapura"],
  ["KRAT-8","Asia/Krasnoyarsk"],
  ["SRT3","America/Paramaribo"],
  ["AMT4","America/Boa Vista"],
  ["IST-5:30","Asia/Kolkata"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Indiana/Indianapolis"],
  ["NPT-5:45","Asia/Kathmandu"],
  ["NST3:30NDT,M3.2.0,M11.1.0","America/St Johns"],
  ["GMT0","Atlantic/Reykjavik"],
  ["CST6CDT,M3.2.0,M11.1.0","America/Matamoros"],
  ["NZST-12NZDT,M9.5.0,M4.1.0/3","Pacific/Auckland"],
  ["MIST-11","Antarctica/Macquarie"],
  ["ART3","America/Argentina/Catamarca"],
  ["CST6CDT,M4.1.0,M10.5.0","America/Merida"],
  ["WAT-1","Africa/Niamey"],
  ["AST4ADT,M3.2.0,M11.1.0","America/Halifax"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Africa/Ceuta"],
  ["CST6CDT,M3.2.0,M11.1.0","America/Chicago"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Stockholm"],
  ["ICT-7","Asia/Vientiane"],
  ["GMT0","Africa/Conakry"],
  ["ART3","America/Argentina/Tucuman"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Berlin"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4","Asia/Nicosia"],
  ["GMT0","Africa/Dakar"],
  ["CAT-2","Africa/Lusaka"],
  ["EST5","America/Cayman"],
  ["EET-2","Asia/Gaza"],
  ["GET-4","Asia/Tbilisi"],
  ["EST5","America/Atikokan"],
  ["BDT-6","Asia/Dhaka"],
  ["PST8PDT,M3.2.0,M11.1.0","America/Tijuana"],
  ["WAT-1","Africa/Douala"],
  ["BRT3","America/Maceio"],
  ["EST-10","Australia/Brisbane"],
  ["HST10","Pacific/Honolulu"],
  ["ART3","America/Argentina/Mendoza"],
  ["AMT4AMST,M10.3.0/0,M2.3.0/0","America/Cuiaba"],
  ["BOT4","America/La Paz"],
  ["GMT0","Africa/Ouagadougou"],
  ["FNT2","America/Noronha"],
  ["PST8PDT,M3.2.0,M11.1.0","America/Los Angeles"],
  ["ART3","America/Argentina/Buenos Aires"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Toronto"],
  ["AST4","America/Grenada"],
  ["EAT-3","Africa/Kampala"],
  ["AST4","America/St Vincent"],
  ["GMT0","Africa/Freetown"],
  ["EST5EDT,M3.2.0,M11.1.0","America/Iqaluit"],
  ["HOVT-7","Asia/Hovd"],
  ["COT5","America/Bogota"],
  ["BRT3","America/Belem"],
  ["CET-1CEST,M3.5.0,M10.5.0/3","Europe/Copenhagen"],
  ["SAST-2","Africa/Johannesburg"],
  ["GILT-12","Pacific/Tarawa"],
  ["GMT0","Africa/Monrovia"],
  ["TJT-5","Asia/Dushanbe"],
  ["GYT4","America/Guyana"],
  ["HKT-8","Asia/Hong Kong"]
];


/*Language*/
sys.allLanguage = {
  al: 'Shqipe',
  ar: 'العربية',
  br: 'Português(Brasil)',
  bu: 'български',
  ch: '简体中文',
  du: 'Nederlands',
  en: 'English',
  en_uk: 'English(UK)',
  en_us: 'English(US)',
  fr: 'Français',
  ge: 'Deutsch',
  gk: 'Ελληνικά',
  hg: 'Magyar',
  it: 'Italiano',
  ja: '日本語',
  mk: 'Македонија',
  pg: 'Português(Portugal)',
  po: 'Polski',
  ro: 'Română',
  ru: 'Русский',
  sp: 'Español',
  sp_latam: 'Español(Latam)',
  sr: 'Srpski',
  tw: '繁體中文',
  ur: 'Українська',
  da: 'Dansk',
  kz: 'Қазақша',
  kr: '한글',
  th: 'ไทย',
  cs: 'čeština',
  hr: 'Hrvatski',
  se: 'Sverige',
  sk: 'Slovensko',
  wr: 'اردو',
  vi: 'Vietnamese',
  tr: 'Turkish',
  si: 'Slovenian',
  fi: 'Suomi',
  no: 'Norge',
  ee: 'eesti',
  fa: 'فارسی',
  lv: 'Latvijas',
  lt: 'Lietuvos',
  id: 'Indonesia'
};
sys.Language = [
  ['en', 'English'],
  ['fr', 'Français'],
  ['it', 'Italiano'],
  ['sp', 'Español']
];
sys.customLanguage = [];
sys.NtpServer1=[
  ["0.openwrt.pool.ntp.org","0.openwrt.pool.ntp.org"],
  ["1.openwrt.pool.ntp.org","1.openwrt.pool.ntp.org"],
  ["0.asia.pool.ntp.org","0.asia.pool.ntp.org"],
  ["1.asia.pool.ntp.org","1.asia.pool.ntp.org"],
  ["0.europe.pool.ntp.org","0.europe.pool.ntp.org"],
  ["1.europe.pool.ntp.org","1.europe.pool.ntp.org"],
  ["0.africa.pool.ntp.org","0.africa.pool.ntp.org"],
  ["1.africa.pool.ntp.org","1.africa.pool.ntp.org"],
  ["0.europe.pool.ntp.org","0.europe.pool.ntp.org"],
  ["1.europe.pool.ntp.org","1.europe.pool.ntp.org"],
  ["0.north-america.pool.ntp.org","0.north-america.pool.ntp.org"],
  ["1.north-america.pool.ntp.org","1.north-america.pool.ntp.org"],
  ["0.oceania.pool.ntp.org","0.oceania.pool.ntp.org"],
  ["1.oceania.pool.ntp.org","1.oceania.pool.ntp.org"],
  ["0.south-america.pool.ntp.org","0.south-america.pool.ntp.org"],
  ["1.south-america.pool.ntp.org","1.south-america.pool.ntp.org"]
];
sys.NtpServer2=[
  ["0.openwrt.pool.ntp.org","0.openwrt.pool.ntp.org"],
  ["1.openwrt.pool.ntp.org","1.openwrt.pool.ntp.org"],
  ["0.asia.pool.ntp.org","0.asia.pool.ntp.org"],
  ["1.asia.pool.ntp.org","1.asia.pool.ntp.org"],
  ["0.europe.pool.ntp.org","0.europe.pool.ntp.org"],
  ["1.europe.pool.ntp.org","1.europe.pool.ntp.org"],
  ["0.africa.pool.ntp.org","0.africa.pool.ntp.org"],
  ["1.africa.pool.ntp.org","1.africa.pool.ntp.org"],
  ["0.europe.pool.ntp.org","0.europe.pool.ntp.org"],
  ["1.europe.pool.ntp.org","1.europe.pool.ntp.org"],
  ["0.north-america.pool.ntp.org","0.north-america.pool.ntp.org"],
  ["1.north-america.pool.ntp.org","1.north-america.pool.ntp.org"],
  ["0.oceania.pool.ntp.org","0.oceania.pool.ntp.org"],
  ["1.oceania.pool.ntp.org","1.oceania.pool.ntp.org"],
  ["0.south-america.pool.ntp.org","0.south-america.pool.ntp.org"],
  ["1.south-america.pool.ntp.org","1.south-america.pool.ntp.org"]
];


export default sys;
